version: '3'

services:
  db: 
    image: mysql
    restart: always
    ports: 
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: insecure
      MYSQL_DATABASE: Organization
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql


  app-server:
    restart: always
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - FLASK_ENV=development
      - MYSQL_DATABASE_HOST=db
      - MYSQL_DATABASE_USER=root
      - MYSQL_DATABASE_PASSWORD=insecure
      - MYSQL_DATABASE_DB=Organization
    volumes:
      - ./server:/app

  app-user-interface:
    restart: always
    build: ./ui
    ports:
      - "3000:3000"
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./ui:/app
